### ISSUE TITLE
add_path on different filesystems

### ISSUE THREAD

**Issue by rptaylor** [cern-mig/python-dirq#6] opened 2022-11-03 03:51 UTC
Could there be an option to QueueSimple.add_path , or a new similar function, that does not require the source and destination to be on the same filesystem?  Why is a hard link used?

Thanks.

**Comment by LionelCons** [comment] 2022-11-04 13:58
In order to prevent race conditions, atomic filesystem operations are used.

These include hard links and renames (within the same filesystem).

If your incoming files reside on another filesystem, you will have to copy them to the same filesystem as the directory queue in order to be able to use the `dirq` module safely.

**Comment by LionelCons** [comment] 2023-06-15 12:22
Closing since the library works as designed.

**Closed** 2023-06-15 12:23 UTC
